### PR TITLE
[change] Use ReconnectingWebsocket to websocket connection #101

### LINKED ISSUE #101: [change] Use ReconnectingWebsocket to websocket connection
https://github.com/openwisp/ansible-openwisp2/pull/321 sets the `websocket_timeout` of daphne to 1 hour (reducing from the 24 hours default value). 
This means that the websocket connection will get terminated abruptly for users after the timeout. To prevent that use ReconnectingWebsocket from https://github.com/joewalnes/reconnecting-websocket which re-establishes the connection when the connection is terminated. 

This library is already used in openwisp-notifications and openwisp-controller.

### PR DESCRIPTION
**Pull request by yashikajotwani12**
Fixes #101

### CODE REVIEW

**Review by pandafy — CHANGES_REQUESTED** [review]
I see following error in web console
Screenshot from 2021-12-23 23-20-28

We will need to update ModelAdmin to so that the reconnecting-websocket file in imported in the template. Adding it here should do it: 


https://github.com/openwisp/django-loci/blob/c62faecf171db5fbe0a93825f2d94671e694b250/django_loci/base/admin.py#L43-L48

**Comment by yashikajotwani12** [comment]
> I see following error in web console Screenshot from 2021-12-23 23-20-28
> 
> We will need to update ModelAdmin to so that the reconnecting-websocket file in imported in the template. Adding it here should do it:
> 
> https://github.com/openwisp/django-loci/blob/c62faecf171db5fbe0a93825f2d94671e694b250/django_loci/base/admin.py#L43-L48

Okay, got it. Thanks

**Comment by yashikajotwani12** [comment]
hello @pandafy, Should I upgrade the Django version too?

**Comment by yashikajotwani12** [comment]
https://github.com/openwisp/django-loci/blob/c62faecf171db5fbe0a93825f2d94671e694b250/django_loci/base/admin.py#L185-L189

And we need to specify here too?

**Review by nemesisdesign — COMMENTED** [review]
@yashikajotwani12 support to the latest django version should have been already added.
Regarding where to place the JS file, please look at the code and test the application to find out where websockets are used and place it in the admin classes which need it.

**Comment by yashikajotwani12** [comment]
> @yashikajotwani12 support to the latest django version should have been already added. Regarding where to place the JS file, please look at the code and test the application to find out where websockets are used and place it in the admin classes which need it.
Okay, I would test the changes and learn about them. Thanks!

**Comment by yashikajotwani12** [comment]
I have tested the changes
Screenshot from 2021-12-28 17-32-56

**Review by pandafy — APPROVED** [review]
LGTM! Good work @yashikajotwani12!

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
