### PR TITLE
upgrade openwisp-utils, add run_qa_checks, reformat code with black

### LINKED ISSUE #60: [qa] Add run-qa-checks, upgrade to openwisp-utils 0.5.1, black formatter
Add run-qa-checks, upgrade to openwisp-utils 0.5.1 and reformat code with black.

### PR DESCRIPTION
**Pull request by morrme**
Resolves #60

### CODE REVIEW

**Comment by morrme** [comment]
I was getting a failure from the flake8 check about missing whitespace after the final comma on lines 28 and 32 of widgets.py.  This is a conflict with the behavior of black, which removes the space.  I changed it manually as a test, but of course it then failed the black check.

**Comment by NoumbissiValere** [comment]
@morrme after upgrading `openwisp-utils` in requirements.txt , did you do `pip install -r requirements.txt requirements-test.txt` to install the upgraded `openwisp-utils`?. If you did, I will advise you fix flake8 and isort errors then use the command `openwisp-qa-format` to handle black errors

**Comment by morrme** [comment]
Hi @NoumbissiValere !
The issue is that the formats are incompatible. 

I added the a line to isort to allow the multi line import format, but it still has an issue with the trailing comma. 

As for the flake8 errors:

```
./django_loci/widgets.py:28:87: E231 missing whitespace after ','
./django_loci/widgets.py:32:66: E231 missing whitespace after ','
```

fixing these manually creates a conflict with black. A decision must be made as to which  rule should override the others. If it is decided that the above error should be ignored, then E231 needs to be added to the rules to skip in the flake8 settings. 

Let me know what you decide.

**Comment by NoumbissiValere** [comment]
Please Squash all your commits together. make it a single commit

**Comment by morrme** [comment]
@NoumbissiValere OK. Has a decision been made on which format rule should be kept/discarded so that I may complete the last change?

**Comment by morrme** [comment]
@nemesisdesign @NoumbissiValere Is there any additional work needed for this one?

**Comment by morrme** [comment]
@nemesisdesign `black` converts everything to double quotes. I didn't change anything manually besides the one sort issue that kept breaking the change. Before the final commit, I ran `openwisp-qa-format ` and `black` to ensure there were no further conflicts.  

`black` does have an option to skip this conversion, it seems. Would you like me to start from the original files again and try that? 

Or, have you now decided to just use `openwsip-qa-format` for all formatting ?

**Comment by NoumbissiValere** [comment]
> @nemesisdesign `black` converts everything to double quotes. I didn't change anything manually besides the one sort issue that kept breaking the change. Before the final commit, I ran `openwisp-qa-format ` and `black` to ensure there were no further conflicts.
> 
> `black` does have an option to skip this conversion, it seems. Would you like me to start from the original files again and try that?
> 
> Or, have you now decided to just use `openwsip-qa-format` for all formatting ?

@morrme don't use the native `black`. `openwisp-qa-format` uses the tweaks we need. so use it to format the code and not native `black`

**Comment by morrme** [comment]
@NoumbissiValere @nemesisdesign   I'm sorry, The initial instructions  were to use `black` so that's how I approached the project.  I will see if I can adjust this.

**Comment by morrme** [comment]
@nemesisdesign @NoumbissiValere  I have made the requested changes.

**Pull request merged**
